// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyWebApiKeyForDevelopmentOnly',
    appId: '1:1234567890:web:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'astrobite-dev',
    authDomain: 'astrobite-dev.firebaseapp.com',
    storageBucket: 'astrobite-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApa1jD5zbTxtR4VyBBEUzZMR8Sr5J3W4',
    appId: '1:925552313324:android:31ea07eec9ad23375d36c9',
    messagingSenderId: '925552313324',
    projectId: 'astrobite-dev',
    storageBucket: 'astrobite-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1u7gh5nVQ3xIqgVyrhi9NdFKFv5n8GgU',
    appId: '1:925552313324:ios:d8bb8269224dff455d36c9',
    messagingSenderId: '925552313324',
    projectId: 'astrobite-dev',
    storageBucket: 'astrobite-dev.firebasestorage.app',
    iosBundleId: 'com.solopreneur.astrobite',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyMacosApiKeyForDevelopment',
    appId: '1:1234567890:ios:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'astrobite-dev',
    storageBucket: 'astrobite-dev.appspot.com',
    iosBundleId: 'com.solopreneur.astrobite',
  );
}
